name: Run AutoCodeReview Bot

on:
  pull_request: 
    branches: 
    - main

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        path: pr

    - name: Checkout Eudoros
      uses: actions/checkout@v4
      with:
        repository: series-ai/eudoros
        ssh-key: ${{ secrets.EUDOROS_SSH_KEY }}
        path: eudoros

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EUDOROS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Install Dependencies
      run: |
        cd $GITHUB_WORKSPACE/pr
        pip install -r AutoCodeReviews/requirements.txt

    - name: Run Diff
      run: |
        cd $GITHUB_WORKSPACE/pr
        git fetch origin main
        git diff origin/main > $GITHUB_WORKSPACE/diffs.txt

    - name: LLM Review
      run: |
        cd $GITHUB_WORKSPACE/eudoros/src/eudoros/tools/autoCodeReview
        export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
        python main.py -d $GITHUB_WORKSPACE/diffs.txt -p $GITHUB_WORKSPACE/pr -o $GITHUB_WORKSPACE/review.json
      continue-on-error: true

    - name: Create Review
      uses: actions/github-script@v6
      if: steps.LLM_Review.outcome == 'success' && github.event_name == 'pull_request'
      with:
        script: |
          const autoFunc = require('${{ github.workspace }}/eudoros/src/eudoros/tools/autoCodeReview/automateReview.js');
          autoFunc.automateReview(context, github, "${{github.event.pull_request.head.sha}}", "${{ github.workspace }}");
      continue-on-error: true
